version: '3'

services:
  frontend:
    build: ./react
    ports:
      - "80:80"

  backend:
    build: ./serve
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=bookclub

  database:
    image: mysql:5.7
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookclub
